# Generated by Django 4.2.14 on 2024-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_ensure_ascii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points_earned',
            field=models.FloatField(default=0),
        ),
    ]
